# Generated by Django 5.0 on 2024-01-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reward_remove_predictionuser_facebook_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
        migrations.AddField(
            model_name='team',
            name='sports',
            field=models.ManyToManyField(related_name='teams', to='app.sports'),
        ),
    ]
