# Generated by Django 5.0 on 2024-01-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_match_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/team_flags/'),
        ),
    ]
