# Generated by Django 5.0 on 2024-01-05 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_team_sport_team_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionuser',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.predictionuser'),
            preserve_default=False,
        ),
    ]
