# Generated by Django 5.0 on 2024-01-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_match_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='sport',
        ),
    ]
