# Generated by Django 5.0 on 2024-01-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_predictionuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionuser',
            name='user',
        ),
    ]
